### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by epsilonqt** [elevenvac/uptime-website-v2#1]
Can you help me? How to setup oauth2 ?

**Comment by elevenski** [comment]
[Discord Developer Portal Oauth2 Click here to view screenshot.](https://cdn.discordapp.com/attachments/767356350735843348/799599508757413928/unknown.png)

server.js 89 Example:
 callbackURL: "https://example.com/callback",

**Comment by elevenski** [comment]
And for the correct operation of the system, please carefully read and apply the Installation section from the link I gave below.
https://github.com/elevenvac/uptime-website-v2#setup

**Comment by epsilonqt** [comment]
Thank you

**Comment by elevenski** [comment]
Don't mention it.
