### ISSUE TITLE
talkedRecentdb is not defined

### ISSUE THREAD

**Issue by Hachiiki** [elevenvac/uptime-website-v2#2]
/home/runner/apptime/server.js:656
    if (talkedRecentdb.has(message.author.id)) {
    ^

ReferenceError: talkedRecentdb is not defined

**Comment by elevenski** [comment]
change "talkedRecentdb" to "talkedRecently".

see new lines:
https://github.com/elevenvac/apptime/blob/main/server.js#L655

**Comment by elevenski** [comment]
solved.
